services:
  python-course:
    build:
      dockerfile: pythonCourse/Dockerfile
    environment:
      MYENV: DEV
    volumes:
      - .:/home/app/webapp
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    